# Generated by Django 4.2.18 on 2026-06-13 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('bandeira', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('elo', 'Elo'), ('amex', 'American Express'), ('hipercard', 'Hipercard'), ('outro', 'Outro')], default='visa', max_length=20)),
                ('tipo', models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito')], default='credito', max_length=10)),
                ('limite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dia_fechamento', models.PositiveSmallIntegerField(blank=True, help_text='Dia do mês em que a fatura fecha (1-31). Apenas para cartões de crédito.', null=True)),
                ('dia_vencimento', models.PositiveSmallIntegerField(blank=True, help_text='Dia do mês em que a fatura vence (1-31).', null=True)),
                ('cor', models.CharField(default='#6C63FF', help_text='Cor hex para exibição no app', max_length=7)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cartão',
                'verbose_name_plural': 'Cartões',
                'ordering': ['responsavel', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icone', models.CharField(blank=True, help_text='Nome do ícone Tabler. Ex: ti-shopping-cart', max_length=50)),
                ('cor', models.CharField(default='#888888', max_length=7)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_pagamento', models.CharField(choices=[('debito', 'Débito'), ('credito_avista', 'Crédito à Vista'), ('credito_parcelado', 'Crédito Parcelado')], max_length=25)),
                ('data_compra', models.DateField(help_text='Data em que a compra foi realizada')),
                ('observacao', models.TextField(blank=True)),
                ('total_parcelas', models.PositiveSmallIntegerField(blank=True, help_text='Número total de parcelas. Preencher apenas se parcelado.', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='gastos.cartao')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='gastos.categoria')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-data_compra', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('apelido', models.CharField(blank=True, max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(help_text='Ex: 1 de 12')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('pago', models.BooleanField(default=False)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='gastos.gasto')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['data_vencimento'],
            },
        ),
        migrations.AddField(
            model_name='gasto',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='gastos.responsavel'),
        ),
        migrations.AddField(
            model_name='cartao',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartoes', to='gastos.responsavel'),
        ),
    ]
