# Generated by Django 4.2.18 on 2026-06-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartao',
            options={'ordering': ['nome'], 'verbose_name': 'Cartão', 'verbose_name_plural': 'Cartões'},
        ),
        migrations.RemoveField(
            model_name='cartao',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='apelido',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='cor',
            field=models.CharField(choices=[('#ef4444', 'Vermelho'), ('#f97316', 'Laranja'), ('#eab308', 'Amarelo'), ('#22c55e', 'Verde'), ('#16a34a', 'Verde Escuro'), ('#06b6d4', 'Ciano'), ('#3b82f6', 'Azul'), ('#6366f1', 'Índigo'), ('#8b5cf6', 'Roxo'), ('#ec4899', 'Rosa'), ('#14b8a6', 'Teal'), ('#f59e0b', 'Âmbar'), ('#84cc16', 'Lima'), ('#64748b', 'Cinza Azul'), ('#78716c', 'Marrom'), ('#888888', 'Cinza')], default='#888888', max_length=7),
        ),
        migrations.RunSQL(
            "UPDATE gastos_categoria SET icone = '' WHERE length(icone) > 10",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='icone',
            field=models.CharField(blank=True, choices=[('🛒', 'Supermercado'), ('🍔', 'Alimentação'), ('🍕', 'Restaurante'), ('☕', 'Café'), ('🍷', 'Bar/Bebida'), ('🚗', 'Transporte'), ('⛽', 'Combustível'), ('🚕', 'Uber/Taxi'), ('✈️', 'Viagem'), ('🏨', 'Hotel'), ('💊', 'Farmácia'), ('🏥', 'Saúde'), ('🎓', 'Educação'), ('📚', 'Livros'), ('🎬', 'Lazer'), ('🎮', 'Games'), ('🎵', 'Música'), ('👕', 'Vestuário'), ('👟', 'Calçados'), ('🏠', 'Casa'), ('🔧', 'Manutenção'), ('⚡', 'Energia'), ('💧', 'Água'), ('📱', 'Celular'), ('💻', 'Tecnologia'), ('💳', 'Assinaturas'), ('🐾', 'Pet'), ('💄', 'Beleza'), ('🎁', 'Presentes'), ('🏋️', 'Academia'), ('💰', 'Outros')], max_length=10),
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('salario', 'Salário'), ('bonus', 'Bônus'), ('outros', 'Outros'), ('saldo_anterior', 'Saldo Mês Anterior')], default='salario', max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('auto_gerada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='gastos.responsavel')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
