# Generated by Django 4.2.18 on 2026-06-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_alter_cartao_options_remove_cartao_responsavel_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE gastos_categoria SET icone = '' WHERE icone IS NOT NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='icone',
            field=models.CharField(blank=True, choices=[('shopping-cart', 'Supermercado'), ('utensils', 'Alimentação / Restaurante'), ('coffee', 'Café'), ('wine', 'Bar / Bebida'), ('car', 'Transporte / Carro'), ('fuel', 'Combustível'), ('map-pin', 'Uber / Taxi'), ('plane', 'Viagem'), ('building', 'Hotel / Construção'), ('pill', 'Farmácia'), ('heart-pulse', 'Saúde'), ('heart', 'Bem-estar'), ('graduation-cap', 'Educação'), ('book-open', 'Livros'), ('tv', 'Streaming / Lazer'), ('gamepad-2', 'Games'), ('music', 'Música'), ('shirt', 'Vestuário'), ('shopping-bag', 'Calçados / Compras'), ('home', 'Casa'), ('wrench', 'Manutenção'), ('zap', 'Energia'), ('droplets', 'Água'), ('smartphone', 'Celular'), ('laptop', 'Tecnologia'), ('credit-card', 'Assinaturas'), ('paw-print', 'Pet'), ('sparkles', 'Beleza'), ('gift', 'Presentes'), ('dumbbell', 'Academia'), ('briefcase', 'Trabalho'), ('baby', 'Filhos'), ('bus', 'Ônibus'), ('receipt', 'Contas'), ('banknote', 'Finanças'), ('shield', 'Seguro'), ('camera', 'Fotografia'), ('star', 'Especial'), ('package', 'Encomendas'), ('wallet', 'Outros')], max_length=50),
        ),
    ]
