# Generated by Django 4.2.18 on 2026-06-14 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gastos', '0003_alter_categoria_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoria',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrada',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas_proprias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gasto',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos_proprios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='usuario_vinculado',
            field=models.ForeignKey(blank=True, help_text='Gastos deste responsável aparecem no dashboard do login vinculado com uma tag.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsaveis_vinculados', to=settings.AUTH_USER_MODEL),
        ),
    ]
