# Generated by Django 4.2.18 on 2026-06-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0004_cartao_user_categoria_user_entrada_user_gasto_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='is_principal',
            field=models.BooleanField(default=False, help_text='Responsável principal gerado automaticamente para o dono da conta.'),
        ),
    ]
