# Generated by Django 4.2.18 on 2026-06-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0006_gasto_cartao_nullable_novos_tipos'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='nome_pessoa',
            field=models.CharField(blank=True, default='', help_text="Nome da pessoa destinatária (para 'Pagamento a Pessoa').", max_length=150),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='tipo_pagamento',
            field=models.CharField(choices=[('debito', 'Débito'), ('credito_avista', 'Crédito à Vista'), ('credito_parcelado', 'Crédito Parcelado'), ('pix', 'Pix / Transferência'), ('dinheiro', 'Dinheiro'), ('emprestimo', 'Empréstimo'), ('pagamento_pessoa', 'Pagamento a Pessoa')], max_length=25),
        ),
    ]
