# Generated by Django 4.2.18 on 2026-06-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0007_gasto_nome_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='tipo_pagamento',
            field=models.CharField(choices=[('debito', 'Débito'), ('credito_avista', 'Crédito à Vista'), ('credito_parcelado', 'Crédito Parcelado'), ('pix', 'Pix / Transferência'), ('emprestimo', 'Empréstimo')], max_length=25),
        ),
    ]
