# Generated by Django 4.2.18 on 2026-06-14 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gastos', '0008_remove_tipos_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='tipo',
            field=models.CharField(choices=[('credito', 'Crédito')], default='credito', max_length=10),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='tipo_pagamento',
            field=models.CharField(choices=[('credito_avista', 'Crédito à Vista'), ('credito_parcelado', 'Crédito Parcelado'), ('pix', 'Pix / Transferência'), ('emprestimo', 'Empréstimo')], max_length=25),
        ),
        migrations.CreateModel(
            name='FaturaPaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('ano', models.PositiveSmallIntegerField()),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas_pagas', to='gastos.cartao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas_pagas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fatura Paga',
                'verbose_name_plural': 'Faturas Pagas',
                'unique_together': {('cartao', 'mes', 'ano', 'user')},
            },
        ),
    ]
