# Generated by Django 4.2.18 on 2026-06-14 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gastos', '0009_remove_debito_add_faturapaga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('banco', models.CharField(blank=True, max_length=100)),
                ('tipo', models.CharField(choices=[('corrente', 'Conta Corrente'), ('poupanca', 'Poupança'), ('salario', 'Conta Salário'), ('investimento', 'Investimento'), ('digital', 'Conta Digital'), ('outro', 'Outro')], default='corrente', max_length=20)),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cor', models.CharField(default='#3b82f6', max_length=7)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='entrada',
            name='conta',
            field=models.ForeignKey(blank=True, help_text='Conta bancária de recebimento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='gastos.conta'),
        ),
        migrations.CreateModel(
            name='PagamentoFeito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pix', 'Pix'), ('emprestimo', 'Empréstimo')], max_length=20)),
                ('mes', models.PositiveSmallIntegerField()),
                ('ano', models.PositiveSmallIntegerField()),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_feitos', to='gastos.responsavel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_feitos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento Feito',
                'verbose_name_plural': 'Pagamentos Feitos',
                'unique_together': {('tipo', 'responsavel', 'mes', 'ano', 'user')},
            },
        ),
    ]
