# Generated by Django 4.2.18 on 2026-06-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0010_contas_pagamentofeito_entrada_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='cor',
            field=models.CharField(choices=[('#ef4444', 'Vermelho'), ('#dc2626', 'Vermelho Escuro'), ('#f97316', 'Laranja'), ('#ea580c', 'Laranja Escuro'), ('#fb923c', 'Salmão'), ('#eab308', 'Amarelo'), ('#f59e0b', 'Âmbar'), ('#fbbf24', 'Dourado'), ('#d97706', 'Caramelo'), ('#22c55e', 'Verde'), ('#16a34a', 'Verde Escuro'), ('#84cc16', 'Lima'), ('#4ade80', 'Verde Claro'), ('#14b8a6', 'Teal'), ('#10b981', 'Esmeralda'), ('#06b6d4', 'Ciano'), ('#0891b2', 'Azul Piscina'), ('#3b82f6', 'Azul'), ('#2563eb', 'Azul Escuro'), ('#60a5fa', 'Azul Claro'), ('#0ea5e9', 'Céu'), ('#6366f1', 'Índigo'), ('#4f46e5', 'Índigo Escuro'), ('#8b5cf6', 'Roxo'), ('#7c3aed', 'Roxo Escuro'), ('#a855f7', 'Lavanda'), ('#ec4899', 'Rosa'), ('#db2777', 'Rosa Escuro'), ('#f472b6', 'Rosa Claro'), ('#64748b', 'Cinza Azul'), ('#475569', 'Ardósia'), ('#78716c', 'Marrom'), ('#57534e', 'Marrom Escuro'), ('#888888', 'Cinza'), ('#6b7280', 'Cinza Médio')], default='#888888', max_length=7),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='icone',
            field=models.CharField(blank=True, choices=[('shopping-cart', 'Supermercado'), ('utensils', 'Alimentação'), ('coffee', 'Café'), ('wine', 'Bar / Bebida'), ('pizza', 'Pizza'), ('sandwich', 'Lanche'), ('salad', 'Dieta'), ('beef', 'Açougue'), ('fish', 'Peixaria'), ('cake', 'Padaria'), ('ice-cream-2', 'Sorvete'), ('cookie', 'Doces'), ('car', 'Carro'), ('fuel', 'Combustível'), ('map-pin', 'Uber / Taxi'), ('plane', 'Viagem'), ('bus', 'Ônibus'), ('train', 'Trem / Metrô'), ('bike', 'Bicicleta'), ('ship', 'Navio'), ('navigation', 'GPS / Rota'), ('home', 'Casa'), ('building-2', 'Apartamento'), ('wrench', 'Manutenção'), ('sofa', 'Móveis'), ('lamp', 'Decoração'), ('thermometer', 'Climatização'), ('zap', 'Energia'), ('droplets', 'Água'), ('flame', 'Gás'), ('trash-2', 'Limpeza'), ('pill', 'Farmácia'), ('heart-pulse', 'Saúde'), ('heart', 'Bem-estar'), ('stethoscope', 'Médico'), ('dumbbell', 'Academia'), ('apple', 'Nutrição'), ('graduation-cap', 'Educação'), ('book-open', 'Livros'), ('pen', 'Papelaria'), ('monitor', 'Curso Online'), ('tv', 'Streaming'), ('gamepad-2', 'Games'), ('music', 'Música'), ('headphones', 'Podcast'), ('camera', 'Fotografia'), ('film', 'Cinema'), ('ticket', 'Shows / Eventos'), ('star', 'Especial'), ('shirt', 'Vestuário'), ('shopping-bag', 'Calçados'), ('watch', 'Acessórios'), ('smartphone', 'Celular'), ('laptop', 'Tecnologia'), ('tablet', 'Tablet'), ('credit-card', 'Assinaturas'), ('briefcase', 'Trabalho'), ('receipt', 'Contas'), ('banknote', 'Finanças'), ('piggy-bank', 'Poupança'), ('coins', 'Investimento'), ('calculator', 'Impostos'), ('shield', 'Seguro'), ('baby', 'Filhos'), ('paw-print', 'Pet'), ('sparkles', 'Beleza'), ('gift', 'Presentes'), ('heart-handshake', 'Doação'), ('building', 'Hotel'), ('map', 'Turismo'), ('luggage', 'Bagagem'), ('package', 'Encomendas'), ('wallet', 'Outros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='conta',
            name='banco',
            field=models.CharField(blank=True, choices=[('', '— Selecione —'), ('nubank', 'Nubank'), ('inter', 'Banco Inter'), ('itau', 'Itaú'), ('bradesco', 'Bradesco'), ('mercadopago', 'Mercado Pago'), ('bb', 'Banco do Brasil'), ('caixa', 'Caixa Econômica'), ('santander', 'Santander'), ('c6', 'C6 Bank'), ('picpay', 'PicPay'), ('xp', 'XP Investimentos'), ('outro', 'Outro')], max_length=20),
        ),
    ]
