# Generated by Django 4.2.18 on 2026-06-15 20:26

from django.db import migrations

MAPPING = {
    'Bradesco': 'bradesco', 'Nubank': 'nubank', 'Itaú': 'itau', 'Itau': 'itau',
    'Banco Inter': 'inter', 'Inter': 'inter', 'Banco do Brasil': 'bb', 'BB': 'bb',
    'Santander': 'santander', 'Caixa': 'caixa', 'Caixa Econômica': 'caixa',
    'C6 Bank': 'c6', 'C6': 'c6', 'PicPay': 'picpay', 'Picpay': 'picpay',
    'XP': 'xp', 'XP Investimentos': 'xp',
    'Mercado Pago': 'mercadopago', 'Mercado pago': 'mercadopago',
}


def normaliza_bancos(apps, schema_editor):
    Conta = apps.get_model('gastos', 'Conta')
    for conta in Conta.objects.all():
        novo = MAPPING.get(conta.banco)
        if novo:
            conta.banco = novo
            conta.save(update_fields=['banco'])


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0011_conta_banco_choices'),
    ]

    operations = [
        migrations.RunPython(normaliza_bancos, migrations.RunPython.noop),
    ]
