# Generated by Django 4.2.18 on 2026-06-16 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gastos', '0014_gasto_pct_divisao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=14)),
                ('saldo_atual', models.DecimalField(decimal_places=2, max_digits=14)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investimentos', to='gastos.conta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investimentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investimento',
                'verbose_name_plural': 'Investimentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='InvestimentoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_anterior', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_novo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('diferenca', models.DecimalField(decimal_places=2, max_digits=14)),
                ('motivo', models.CharField(blank=True, max_length=300)),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('investimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='gastos.investimento')),
            ],
            options={
                'verbose_name': 'Histórico de Investimento',
                'verbose_name_plural': 'Histórico de Investimentos',
                'ordering': ['-data_movimentacao'],
            },
        ),
    ]
