# Generated by Django 4.2.18 on 2026-06-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0015_investimento_e_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimento',
            name='data_liquidacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investimento',
            name='liquidado',
            field=models.BooleanField(default=False),
        ),
    ]
