# Generated by Django 4.2.18 on 2026-06-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0019_gasto_debito_conta_origem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='nome_pessoa',
        ),
        migrations.AlterField(
            model_name='investimentohistorico',
            name='tipo',
            field=models.CharField(choices=[('inicial', 'Aporte Inicial'), ('aporte', 'Aporte'), ('saque', 'Saque'), ('rendimento', 'Rendimento'), ('ajuste_saldo', 'Ajuste de Saldo'), ('liquidacao', 'Liquidação')], default='rendimento', max_length=15),
        ),
    ]
