# Generated by Django 4.2.18 on 2026-06-28 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gastos', '0025_ajuste_fatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='tipo_pagamento',
            field=models.CharField(choices=[('credito_avista', 'Crédito à Vista'), ('credito_parcelado', 'Crédito Parcelado'), ('recorrente', 'Compra Recorrente'), ('pix', 'Pix / Transferência'), ('debito', 'Débito'), ('ajuste_fatura', 'Ajuste de Fatura')], db_index=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='pagamentofeito',
            name='tipo',
            field=models.CharField(choices=[('pix', 'Pix'), ('acerto', 'Acerto')], max_length=20),
        ),
        migrations.CreateModel(
            name='LogErro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tipo', models.CharField(choices=[('500', 'Erro interno (500)'), ('webhook', 'Erro Webhook WhatsApp'), ('llm', 'Erro LLM'), ('outro', 'Outro')], db_index=True, default='500', max_length=20)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('exception_type', models.CharField(blank=True, max_length=200)),
                ('exception_message', models.TextField(blank=True)),
                ('traceback', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erros_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Erro',
                'verbose_name_plural': 'Logs de Erro',
                'ordering': ['-timestamp'],
            },
        ),
    ]
