FROM python:3.11-alpine

RUN apk add --no-cache docker-cli bc

WORKDIR /app/scripts
COPY scripts/monitor_server.sh monitor_server.sh
COPY scripts/send_report.py    send_report.py
COPY scripts/scheduler.py      scheduler.py

RUN chmod +x monitor_server.sh

CMD ["python3", "/app/scripts/scheduler.py"]
